## Predict on new data

In [6]:
# EDA and data handling
import numpy as np 
import pandas as pd 
import pickle
import os
import matplotlib.pyplot as plt

# Modeling
import sklearn
from sklearn.model_selection import train_test_split, GridSearchCV 
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier 
from sklearn import metrics

In [7]:
# open the pickled word vector file
file = open('../vectorizer.pkl', 'rb')
tvec_pkl=pickle.load(file)
file.close()

In [8]:
type(tvec_pkl)

sklearn.feature_extraction.text.TfidfVectorizer

In [12]:
# newdata = train[train['target']==1]['overview'].sample(1).values
newdata = ['this is a test this is just a test funny funny joke ha']
tvec_test=tvec_pkl.transform(newdata)
print(str(tvec_pkl.transform(newdata)))

  (0, 134579)	0.511745341230187
  (0, 72899)	0.19080085773998523
  (0, 72204)	0.36424295772235477
  (0, 59785)	0.38305808238609035
  (0, 54529)	0.6498502224999599


In [9]:
# open the pickled RF model file
file = open(f'trained_rf_model.pkl', 'rb')
rf_model_pickled=pickle.load(file)
file.close()

FileNotFoundError: [Errno 2] No such file or directory: 'trained_rf_model.pkl'

In [7]:
# new predictions
preds_test=rf_model_pickled.predict(tvec_test)
preds_test

array([0])

In [9]:
# read in the holdout dataset (from TMDB)
holdout_df=pd.read_csv('../data/test_plots.csv')
holdout_df=holdout_df.dropna(how='any')
# # vectorize the new text data
tvec_01 = tvec_pkl.transform(holdout_df['overview'])
# predict using the model 
preds_01=rf_model_pickled.predict(tvec_01)
# create a new column with the predictions
holdout_df['preds'] = preds_01
# examine
holdout_df['preds'].value_counts()

0    315
1     12
Name: preds, dtype: int64

In [10]:
# examine
pd.set_option('display.max_colwidth', 500)
holdout_df[holdout_df['preds']==1][['title','overview']]

title  \
15   Once Upon a Time… in Hollywood   
30                          Aladdin   
51                     Dark Phoenix   
75                   Pain and Glory   
81                Bohemian Rhapsody   
84                   Last Christmas   
194                Ready Player One   
210        The Grand Budapest Hotel   
212                       Long Shot   
229    Kingsman: The Secret Service   
261         The Angry Birds Movie 2   
269                        Sex Tape   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                overview  
15                                                                                                                                                                         Los Angeles, 1969. TV star Rick Dalton, a struggling actor specializing in westerns, and stuntman Cliff Booth, his best friend, try to survive in a constantly changing movie industry. Dalton is the neighbor of the young and promising actress and model Sharon Tate, who has just married the prestigious Polish director Roman Polanski…  
30                                                                                                                                                                                                                                                                  A kindhearted street urchin named Aladdin embarks on a magical adventure after finding a lamp that releases a wisecracking genie while a power-hungry Grand Vizier vies for the same lamp that has the power to make their deepest wishes come true.  
51                                               The X-Men face their most formidable and powerful foe when one of their own, Jean Grey, starts to spiral out of control. During a rescue mission in outer space, Jean is nearly killed when she's hit by a mysterious cosmic force. Once she returns home, this force not only makes her infinitely more powerful, but far more unstable. The X-Men must now band together to save her soul and battle aliens that want to use Grey's new abilities to rule the galaxy.  
75                                                                            Salvador Mallo, a filmmaker in the twilight of his career, remembers his life: his mother, his lovers, the actors he worked with. The sixties in a small village in Valencia, the eighties in Madrid, the present, when he feels an immeasurable emptiness, facing his mortality, the incapability of continuing filming, the impossibility of separating creation from his own life. The need of narrating his past can be his salvation.  
81                                                                                                 Singer Freddie Mercury, guitarist Brian May, drummer Roger Taylor and bass guitarist John Deacon take the music world by storm when they form the rock 'n' roll band Queen in 1970. Hit songs become instant classics. When Mercury's increasingly wild lifestyle starts to spiral out of control, Queen soon faces its greatest challenge yet – finding a way to keep the band together amid the success and excess.  
84                                                                                                                                                                                                                                                                                    Kate is a young woman who has a habit of making bad decisions, and her last date with disaster occurs after she accepts work as Santa's elf for a department store. However, after she meets Tom there, he

In [12]:
# entirely new text
tryagain=['Funny funny joke joke laugh girlfriend relationship attractive wants humor hilarious fun']
tvec_02 = tvec_pkl.transform(tryagain)
preds_02=rf_model_pickled.predict(tvec_02)
preds_02

array([0])

In [14]:
grabtext=['Florence Forrest a Gidget-like character determined to learn to surf, and earns the nickname "Chicklet" from the surfer guys. However Chicklet begins displaying multiple personalities, experiences inexplicable blackouts, and fears that she might be the one responsible for a ']
grabtext=['Florence Forrest a Gidget-like character determined to learn to surf, and earns the nickname "Chicklet" from the surfer guys. However Chicklet begins displaying multiple personalities, experiences inexplicable blackouts, and fears responsible']
tvec_03 = tvec_pkl.transform(grabtext)
preds_03=rf_model_pickled.predict(tvec_03)
preds_03

array([0])

In [15]:
# remove the pickle files, they are already zipped.
os.remove('vectorizer.pkl')
os.remove('trained_rf_model.pkl')